### ISSUE TITLE
Extend expected errors of jwt-client

### ISSUE THREAD

**Issue by VitaliiNobis** [kofile/jwt-client#1]
On service side we need to provide proper response with 400/401 status code if token doesn't have valid payload structure or has missing fields. But current errors are generic and cannot be differentiated from other runtime errors.

As a solution you can add some 'marker' or flag to error objects.
Also you can move checks from getter functions to 'jwtClient' function. In such case we will wrap creation of jwtClient in try-catch and handle errors there.

**Comment by neezer** [comment]
Good feedback. I'll work on getting it implemented, @VitaliiNobis
